### ISSUE TITLE
allow reorganizing stacks and cards 

### ISSUE THREAD

**Issue by ferdiga** [juliushaertl/deck#36] opened 2017-02-05 01:09 UTC
IMO important enhancements
allow moving cards in stack and between stacks
allow moving stacks
allow sub stacks

**Comment by juliushaertl** [comment] 2017-02-05 12:57
>allow moving cards in stack and between stacks

This is already possible by dragging them around.

>allow moving stacks

There is already an issue for that https://github.com/juliushaertl/deck/issues/16

>allow sub stacks

Seems to me like a duplicate of https://github.com/juliushaertl/deck/issues/32 If not, feel free to reopen an issue for this one with a more detailed description.

**Closed by juliushaertl** 2017-02-05 12:57 UTC

**Comment by ferdiga** [comment] 2017-02-05 13:08
moving cards is possible - I was looking for a handle to grab. 
nevertheless during the move operation the card gets displayed below the left most stack
Hence I thought this feature is not implemented.

**Comment by juliushaertl** [comment] 2017-02-05 22:00
> nevertheless during the move operation the card gets displayed below the left most stack

Can you post a screenshot of that and some information on the browser you are using? This doesn't sound like it should be that way. :wink:

**Comment by juliushaertl** [comment] 2017-02-05 22:03
Ah never mind. I could reproduce it. #39 is the new issue for that.
